services:
  pihole2:
    extends:
      file: ../shared.yml
      service: main-shared
    # network_mode: host
    container_name: pihole2
    hostname: pihole2
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "853:853"
    # cap_add:
    #   - NET_ADMIN
    # dns:
    #   - 127.0.0.1
    #   - 1.1.1.1
    volumes:
      - ${CONF_DIR}/pihole/etc/:/etc/pihole/
      - ${CONF_DIR}/pihole/dnsmasqd/:/etc/dnsmasq.d/
      - ${CONF_DIR}/pihole/log/pihole/:/var/log/pihole/
    env_file: pihole.env