services:
  pihole2:
    extends:
      file: ../shared.yml
      service: main-shared
    network_mode: host
    container_name: pihole2
    hostname: pihole2
    image: pihole/pihole:latest
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - ${CONF_DIR}/pihole/etc/:/etc/pihole/
      - ${CONF_DIR}/pihole/dnsmasqd/:/etc/dnsmasq.d/
      - ${CONF_DIR}/pihole/log/pihole/:/var/log/pihole/
    environment:
      - FTLCONF_LOCAL_IPV4=${PIHOLE_IP}
      - PROXY_LOCATION=pihole2
      - VIRTUAL_HOST=pihole2.home
      - VIRTUAL_PORT=80
      - TZ=${TZ}
      - WEBPASSWORD=v%JW3kr4UnPHILlf
      - PIHOLE_DNS_=192.168.2.1
      - DNS_FQDN_REQUIRED=false
      - DNS_BOGUS_PRIV=true
        #- DNSMASQ_USER=root
        #- PIHOLE_UID=0
      - REV_SERVER=true
      - REV_SERVER_TARGET=192.168.2.1
      - REV_SERVER_DOMAIN=home
      - REV_SERVER_CIDR=192.168.2.0/23
      - CORS_HOSTS=dashboard.benweb.eu
    labels:
    ## Only monitor with Watchtower, do not auto-update
      # - "com.centurylinklabs.watchtower.monitor-only=true"
      ### HomePage
      - "homepage.group=Network"
      - "homepage.name=PiHole 2"
      - "homepage.icon=pi-hole.png"
      - "homepage.weight=2"
      - "homepage.href=https://pihole2.benweb.eu"
      - "homepage.ping=https://pihole2.benweb.eu"
      - "homepage.description=Secondary"
      - "homepage.widget.type=pihole"
      - "homepage.widget.url=http://pihole2.home"
      - "homepage.widget.key=4769d913c682e004664355c91cd7307399d13d1f363d55bd777b9d1d9c186138"

# Docker Proxy
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    hostname: dockerproxy
    extends:
      file: ../shared.yml
      service: main-shared
    network_mode: host
    environment:
        - CONTAINERS=1 # Allow access to viewing containers
        - POST=0 # Disallow any POST operations (effectively read-only)
    # ports:
    #     - 2375:2375
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro

# Glances - Server monitoring
  glances:
    image: nicolargo/glances
    container_name: pihole-glances
    hostname: pihole-glances
    extends:
      file: ../shared.yml
      service: main-shared
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    labels:
      ### HomePage
      - "homepage.group=PiHolePi"
      - "homepage.name=Info"
      - "homepage.icon=glances.png"
      - "homepage.weight=1"
      - "homepage.href=https://pihole-glances.${DOMAINNAME}"
      - "homepage.ping=https://pihole-glances.${DOMAINNAME}"
      - "homepage.widget.type=glances"
      - "homepage.widget.url=https://pihole-glances.${DOMAINNAME}"
      - "homepage.widget.metric=info"