services:
  pihole:
    extends:
      file: ../shared.yml
      service: main-shared
    network_mode: host
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - ${CONF_DIR}/pihole/etc/:/etc/pihole/
      - ${CONF_DIR}/pihole/dnsmasqd/:/etc/dnsmasq.d/
      - ${CONF_DIR}/pihole/log/pihole/:/var/log/pihole/
    environment:
      - ServerIP=${PIHOLE_IP}
      - PROXY_LOCATION=pihole2
      - VIRTUAL_HOST=pihole2.home
      - VIRTUAL_PORT=80
      - TZ=${TZ}
      - WEBPASSWORD=v%JW3kr4UnPHILlf
      - DNS1=192.168.2.1
      - DNS2=no
      - DNS_FQDN_REQUIRED=false
      - DNS_BOGUS_PRIV=true
      - DNSMASQ_USER=root
      - REV_SERVER=true
      - REV_SERVER_TARGET=192.168.2.1
      - REV_SERVER_DOMAIN=home
      - REV_SERVER_CIDR=192.168.2.0/24
      - CORS_HOSTS=dashboard.benweb.eu
    # labels:
    ## Only monitor with Watchtower, do not auto-update
      # - "com.centurylinklabs.watchtower.monitor-only=true"
